eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwtmicroservice
    username: root
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8060