eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userservice
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: bearservice
          uri: lb://BEAR-SERVICE
          predicates:
            - Path=/bear/**
          filters:
            - AuthenticationFilter
server:
  port: 8222